from tools.cho_integral.cal_chi import get_cal_chi
from tools.cho_integral.Choquet_integral_NN_LJModified import Choquet_Integral_NN, train_chinn
from tools.cho_integral.Choquet_integral_QP_LJModified import Choquet_Integral_QP
from tools.cho_integral.get_fm import init_FM